/**************************************************************************************
* 因为emWin显示只支持UTF-8编码格式的中文，如果希望直接显示在Keil直接输入的中文，      *
*            比如使用：GUI_DispStringHCenterAt("流水灯",110,120);                     *
* 该文件必须以UTF-8编码格式，不然中文无法正常显示。                                   *
*                                                                                     *
* 如果只是个别例程出现中文显示乱码（如果所有例程都无法显示中文可能是字库问题），      *
* 把对应的例程文件(比如LEDapp.c)用电脑的记事本软件打开，然后选择另存为，在弹出对      *
* 话框中“保存(S)"按钮的左边有个"编码(E)"选项，选择"UTF-8",然后同样保存为同名称的      *
* C语言文件(覆盖原来文件)，再编译。                                                   *
*                                                                                     *
* 如果编译工程时出现下面类似错误也是该文件编码格式问题,必须把文件保存为UTF-8格式      *
* 再编译                                                                              *
* ..\..\User\app\LEDapp.c(275): error:  #8: missing closing quote                     *
*        GUI_DispStringHCenterAt("娴?姘?鐏?",110,120);                                *
* ..\..\User\app\LEDapp.c(276): error:  #165: too few arguments in function call      *
*        GUI_DispStringHCenterAt("瑙?鎽?鍋?宸?澶?鎵?闇€瑕?瑙?鎽?鏍?鍑?",110,215);     *
* ..\..\User\app\LEDapp.c(276): error:  #18: expected a ")"                           *
*        GUI_DispStringHCenterAt("瑙?鎽?鍋?宸?澶?鎵?闇€瑕?瑙?鎽?鏍?鍑?",110,215);     *
*                                                                                     *
* 修改文件后编译就出错这是Keil5软件问题(Keil4没这问题)，推荐使用其他程序编辑工具，    *
* 只用Keil5完成编译和下载工作。                                                       *
***************************************************************************************
*                      实验平台: 野火STM32 ISO 开发板                                 *
*                      论    坛: http://www.chuxue123.com                             *
*                      淘    宝: http://firestm32.taobao.com                          *
*                      邮    箱: wildfireteam@163.com                                 *
***************************************************************************************
*/
/**************************************************************************************
*                                                                                     *
*                SEGGER Microcontroller GmbH & Co. KG                                 *
*        Solutions for real time microcontroller applications                         *
*                                                                                     *
***************************************************************************************
*                                                                                     *
* C-file generated by:                                                                *
*                                                                                     *
*        GUI_Builder for emWin version 5.22                                           *
*        Compiled Jul  4 2013, 15:16:01                                               *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG                                *
*                                                                                     *
***************************************************************************************
*                                                                                     *
*        Internet: www.segger.com  Support: support@segger.com                        *
*                                                                                     *
***************************************************************************************
*/
// USER START (Optionally insert additional includes)
#include "includes.h"
#include  "app.h"
#include <string.h>
// USER END
/**************************************************************************************
*
*       Defines
*
***************************************************************************************
*/


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
// USER START (Optionally insert additional static data)
extern GUI_FONT     XBF_Font;
extern __IO uint8_t key_flag;


void FUN_InputFingerprint(void);
void Wipe_FingerprintData(void);

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
const GUI_WIDGET_CREATE_INFO _aDialogCreateWiFi[] = {
	{FRAMEWIN_CreateIndirect, "WiFi", 0, 0, 0, 240, 320, 0, 0x0, 0 },
	{TEXT_CreateIndirect, 	"Text", GUI_ID_TEXT0, 	10, 35, 160, 40, 0, 0x6, 0 }, 
  {TEXT_CreateIndirect, 	"Text", GUI_ID_TEXT1, 	10, 75, 160, 40, 0, 0x6, 0 },
	{BUTTON_CreateIndirect, "WiFiLink", GUI_ID_BUTTON3, 45, 130, 150, 40, 0, 0x0, 0 },
  /*{ BUTTON_CreateIndirect, "Add", GUI_ID_BUTTON0, 10, 10, 200, 40, 0, 0x0, 0 },//x位置   y位置   长  高
  { BUTTON_CreateIndirect, "Del", GUI_ID_BUTTON1, 10, 50, 200, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Clear", GUI_ID_BUTTON2, 10, 90, 200, 40, 0, 0x0, 0 },*/
//	{ SLIDER_CreateIndirect, "LED_Slider", GUI_ID_SLIDER0, 35, 135, 170, 40, 0, 0x0, 0 },
//	{ BUTTON_CreateIndirect, "Calibration", GUI_ID_BUTTON2, 118-60, 240, 120, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/

u8 LinkFlag = 0;
static void _cbDialogWiFi(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER END

  switch (pMsg->MsgId) 
  {
	  case WM_DELETE:
		// USER START (Optionally insert additional code for further widget initialization)
		  OS_INFO("KEYapp delete\n");
		  Flag_ICON102 = 0;
			LinkFlag = 0;
//			LED1_OFF;LED2_OFF;LED3_OFF;
		// USER END
		    break;
	  case WM_INIT_DIALOG:
		//
		// Initialization of 'KEY TEST'
		//
		hItem = pMsg->hWin;
		FRAMEWIN_SetTextColor(hItem,GUI_DARKGRAY);
		FRAMEWIN_SetFont(hItem, GUI_FONT_16B_ASCII);
		FRAMEWIN_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,0);
		FRAMEWIN_SetTitleHeight(hItem, 20);
    
		if (ESP8266_Cmd("AT+CIPSTATUS", "STATUS:5", NULL, 200))    // 还没有连接到 WiFi
		{
			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT0);
			TEXT_SetFont(hItem, &XBF_Font);
			TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			TEXT_SetText(hItem, "云连接失败");

			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT1);
			TEXT_SetFont(hItem, &XBF_Font);
			TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			TEXT_SetText(hItem, "WiFi未连接");
		}
		else if (ESP8266_Cmd("AT+CIPSTATUS", "STATUS:2", NULL, 200))    // 连接到 WiFi
		{
			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT0);
			TEXT_SetFont(hItem, &XBF_Font);
			TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			TEXT_SetText(hItem, "云连接失败");

			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT1);
			TEXT_SetFont(hItem, &XBF_Font);
			TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			TEXT_SetText(hItem, "WiFi已连接");
		}
		else
		{
			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT0);
			TEXT_SetFont(hItem, &XBF_Font);
			TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			TEXT_SetText(hItem, "云连接成功");

			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT1);
			TEXT_SetFont(hItem, &XBF_Font);
			TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			TEXT_SetText(hItem, "WiFi已连接");
		}

		
		
		hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON3);
		BUTTON_SetText(hItem, "开始手机配网");
		BUTTON_SetFont(hItem, &XBF_Font);
		
		// USER START (Optionally insert additional code for further widget initialization)
		// USER END
		break;

	  case WM_NOTIFY_PARENT:
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch(Id) {
		  case GUI_ID_BUTTON3: // Notifications sent by '确定'
		  switch(NCode) {
		  case WM_NOTIFICATION_CLICKED:

			break;
		  case WM_NOTIFICATION_RELEASED:
            LinkFlag = 1;
            hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT0);
			TEXT_SetFont(hItem, &XBF_Font);
			TEXT_SetText(hItem, "云连接已断开");

			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT1);
			TEXT_SetFont(hItem, &XBF_Font);
			TEXT_SetText(hItem, "WiFi连接已断开");

            hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON3);
            BUTTON_SetText(hItem, "手机配网中...");
            BUTTON_SetFont(hItem, &XBF_Font);
            WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON0));    // 无效窗口直到配置成功
			// USER END
			break;
		  case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END			    
				break;
		  }
		  break;
		// USER START (Optionally insert additional code for further Ids)
		// USER END
		}
		break;
	  // USER START (Optionally insert additional message handling)
		case WM_PAINT:	
			GUI_SetBkColor(APPBKCOLOR);
			GUI_SetColor(GUI_MAGENTA);
			GUI_SetColor(APPTEXTCOLOR);
			GUI_Clear();
		break;
	  // USER END
	  default:
		WM_DefaultProc(pMsg);
		break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateKEY TEST
*/

#define    	USING_CLOUD    0    // 1 : 使用云    0：使用自定义服务器

void FUN_ICON102Clicked(void)
{
	OS_ERR err;
	LinkFlag = 0;
    u8 WiFiFlag = 0;
    WM_HWIN hWin;
    WM_HWIN hItem;
	hWin = GUI_CreateDialogBox(_aDialogCreateWiFi, GUI_COUNTOF(_aDialogCreateWiFi), _cbDialogWiFi, WM_HBKWIN, 0, 0);
	OS_INFO("WiFi create\n");
	while(Flag_ICON102)
	{
        while(LinkFlag)     // 使用手机配网
        {
			OS_TaskSuspend(&AppTaskWiFiTCB, &err);    // 挂起 WiFi 任务

            switch( WiFiFlag)
            {
                case 0:    // 断开与云连接
				#if    USING_CLOUD

                    OS_ESP8266_Cmd("AT+ATKCLDCLS", NULL, NULL, 1500);    // 断开与云连接
					ESP8266_Cmd("ATE0", NULL, NULL, 500);    // 关闭 WiFi 回显
                    WiFiFlag = 1;

				#else

					OS_ESP8266_Cmd("+++", NULL, NULL, 1500);    // 退出透传模式
					ESP8266_Cmd("ATE0", NULL, NULL, 500);       // 关闭 WiFi 回显
                    WiFiFlag = 1;

				#endif

                break;
                
                case 1:    // 恢复出厂设置
                    if (ESP8266_Cmd("AT+RESTORE", "OK", NULL, 500))    // 恢复出厂设置
                    {
						ESP8266_Cmd("ATE0", NULL, NULL, 500);    // 关闭 WiFi 回显
                        WiFiFlag = 2;
                    }
                    else
                    {
                        WiFiFlag = 0;
                    }
                break;
                    
                case 2:    // 设置模块为 STA 模式
                    if (ESP8266_Cmd("AT+CWMODE=1", "OK", NULL, 1500))    // 设置模块为 STA 模式
                    {
						// ESP8266_Cmd("AT+RST", "OK", NULL, 1500);
                        WiFiFlag = 3;
                    }
                    else
                    {
                        WiFiFlag = 0;
                    }
                break;
                
                case 3:    // 设置模块为 Airkiss 模式
                    if (ESP8266_Cmd("AT+CWSTARTSMART=2", "OK", NULL, 1500))    // 设置模块为 Airkiss 模式
                    {
                        WiFiFlag = 4;
                        USART1_RX_Len = 0;
                    }
                    else
                    {
                        WiFiFlag = 0;
                    }
                break;
                    
                case 4:    // 设置模块 连接服务器
                    if (USART1_RX_Len != 0)    // 模块连接 wifi 成功
                    {
						hItem = WM_GetDialogItem(hWin, GUI_ID_TEXT1);
									TEXT_SetFont(hItem, &XBF_Font);
									TEXT_SetText(hItem, "WiFi已连接");

						#if    USING_CLOUD    /* 使用云 */
                        if (ESP8266_Cmd("AT+ATKCLDSTA=\"79459799892981462448\",\"87654321\"", "OK", "CLOUD CONNECTED", 500))    // 连接云服务器
                        {
                            /* 云连接成功 */
                            hItem = WM_GetDialogItem(hWin, GUI_ID_TEXT0);
                            TEXT_SetFont(hItem, &XBF_Font);
                            TEXT_SetText(hItem, "云连接成功");

                            hItem = WM_GetDialogItem(hWin, GUI_ID_TEXT1);
                            TEXT_SetFont(hItem, &XBF_Font);
                            TEXT_SetText(hItem, "WiFi已连接");
                            
                            hItem = WM_GetDialogItem(hWin, GUI_ID_BUTTON3);
                            BUTTON_SetText(hItem, "开始手机配网");
                            BUTTON_SetFont(hItem, &XBF_Font);
                            LinkFlag = 0;    // 配网成功
                            WiFiFlag = 0;

							OSTaskResume(&AppTaskWiFiTCB, &err);    // 恢复 WiFi 任务
                        }
						#else    /* 使用自定义服务器 */
						switch( WiFiFlag)
            			{
							case 4:     // 连接服务器
								if (ESP8266_Cmd("AT+CIPSTART=\"TCP\",\"172.20.10.12\",8080", "OK", "CONNECT", 500))    // 连接自定义服务器
								{
									WiFiFlag = 5;
								}
								else
								{
									WiFiFlag = 4;
								}
								break;

							case 5:    // 开启透传模式
								if (ESP8266_Cmd("AT+CIPMODE=1", "OK", NULL, 500))    // 连接自定义服务器
								{
									WiFiFlag = 6;
								}
								else
								{
									WiFiFlag = 4;
								}
								break;

							case 6:    // 开始透传
								if (ESP8266_Cmd("AT+CIPSEND", "OK", NULL, 500))    // 连接自定义服务器
								{
									/* 云连接成功 */
									hItem = WM_GetDialogItem(hWin, GUI_ID_TEXT0);
									TEXT_SetFont(hItem, &XBF_Font);
									TEXT_SetText(hItem, "服务器连接成功");

									
									
									hItem = WM_GetDialogItem(hWin, GUI_ID_BUTTON3);
									BUTTON_SetText(hItem, "开始手机配网");
									BUTTON_SetFont(hItem, &XBF_Font);
									LinkFlag = 0;    // 配网成功
									WiFiFlag = 0;

									ESP8266_Cmd("AT+SAVETRANSLINK=1,\"192.168.43.199\",8080,\"TCP\"", NULL, NULL, 500);

									OSTaskResume(&AppTaskWiFiTCB, &err);    // 恢复 WiFi 任务
								}
								else
								{
									WiFiFlag = 4;
								}
								break;
						}
						#endif
                    }

                break;
            }
            GUI_Delay(10);
        }
    
		GUI_Delay(10);
	}
}

/*************************** End of file ****************************/
