/**************************************************************************************
* 因为emWin显示只支持UTF-8编码格式的中文，如果希望直接显示在Keil直接输入的中文，      *
*            比如使用：GUI_DispStringHCenterAt("流水灯",110,120);                     *
* 该文件必须以UTF-8编码格式，不然中文无法正常显示。                                   *
*                                                                                     *
* 如果只是个别例程出现中文显示乱码（如果所有例程都无法显示中文可能是字库问题），      *
* 把对应的例程文件(比如LEDapp.c)用电脑的记事本软件打开，然后选择另存为，在弹出对      *
* 话框中“保存(S)"按钮的左边有个"编码(E)"选项，选择"UTF-8",然后同样保存为同名称的      *
* C语言文件(覆盖原来文件)，再编译。                                                   *
*                                                                                     *
* 如果编译工程时出现下面类似错误也是该文件编码格式问题,必须把文件保存为UTF-8格式      *
* 再编译                                                                              *
* ..\..\User\app\LEDapp.c(275): error:  #8: missing closing quote                     *
*        GUI_DispStringHCenterAt("娴?姘?鐏?",110,120);                                *
* ..\..\User\app\LEDapp.c(276): error:  #165: too few arguments in function call      *
*        GUI_DispStringHCenterAt("瑙?鎽?鍋?宸?澶?鎵?闇€瑕?瑙?鎽?鏍?鍑?",110,215);     *
* ..\..\User\app\LEDapp.c(276): error:  #18: expected a ")"                           *
*        GUI_DispStringHCenterAt("瑙?鎽?鍋?宸?澶?鎵?闇€瑕?瑙?鎽?鏍?鍑?",110,215);     *
*                                                                                     *
* 修改文件后编译就出错这是Keil5软件问题(Keil4没这问题)，推荐使用其他程序编辑工具，    *
* 只用Keil5完成编译和下载工作。                                                       *
***************************************************************************************
*                      实验平台: 野火STM32 ISO 开发板                                 *
*                      论    坛: http://www.chuxue123.com                             *
*                      淘    宝: http://firestm32.taobao.com                          *
*                      邮    箱: wildfireteam@163.com                                 *
***************************************************************************************
*/
/**************************************************************************************
*                                                                                     *
*                SEGGER Microcontroller GmbH & Co. KG                                 *
*        Solutions for real time microcontroller applications                         *
*                                                                                     *
***************************************************************************************
*                                                                                     *
* C-file generated by:                                                                *
*                                                                                     *
*        GUI_Builder for emWin version 5.22                                           *
*        Compiled Jul  4 2013, 15:16:01                                               *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG                                *
*                                                                                     *
***************************************************************************************
*                                                                                     *
*        Internet: www.segger.com  Support: support@segger.com                        *
*                                                                                     *
***************************************************************************************
*/
// USER START (Optionally insert additional includes)
#include "includes.h"
#include  "app.h"
#include <string.h>
// USER END
/**************************************************************************************
*
*       Defines
*
***************************************************************************************
*/


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
// USER START (Optionally insert additional static data)
extern GUI_FONT     XBF_Font;
extern __IO uint8_t key_flag;


void PasswordManagement(void);
void Wipe_FingerprintData(void);

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
extern const GUI_WIDGET_CREATE_INFO _aDialogCreateSettings[]=
{
	{ FRAMEWIN_CreateIndirect, "Settings", 0, 0, 0, 240, 320, 0, 0x0, 0 },
	{EDIT_CreateIndirect, 	"Edit", GUI_ID_EDIT1, 	10, 35, 160, 40, 0, 0x6, 0 }, 
	{ BUTTON_CreateIndirect, "Del", GUI_ID_BUTTON3, 180, 35, 40, 40, 0, 0x0, 0 },
};

static const GUI_WIDGET_CREATE_INFO _aDialogCreateIN[] = {
	{ FRAMEWIN_CreateIndirect, "Password Management", 0, 0, 0, 240, 320, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Add", GUI_ID_BUTTON0, 10, 10, 200, 40, 0, 0x0, 0 },//x位置   y位置   长  高
	{ BUTTON_CreateIndirect, "Del", GUI_ID_BUTTON1, 10, 50, 200, 40, 0, 0x0, 0 },
	/*{ BUTTON_CreateIndirect, "Clear", GUI_ID_BUTTON2, 10, 90, 200, 40, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, 	"state", GUI_ID_TEXT0, 	140, 18, 55, 20, 0, 0x64, 0 }, 
	{ BUTTON_CreateIndirect, "Del", GUI_ID_BUTTON4, 50, 40, 80, 40, 0, 0x0, 0 },*/
//	{ SLIDER_CreateIndirect, "LED_Slider", GUI_ID_SLIDER0, 35, 135, 170, 40, 0, 0x0, 0 },
//	{ BUTTON_CreateIndirect, "Calibration", GUI_ID_BUTTON2, 118-60, 240, 120, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

u8 PasswordManagement_Loop = 0;

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static u8 OK_Flag = 0;
static void _cbDialogSET(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  OS_ERR      err;
  static u8 PasswordFlags = 0;
  // USER START (Optionally insert additional variables)
  uint16_t messagesP[2];
  char EnterPassword[7];    // 输入的密码
  u8 Password[7];
  // USER END

  switch (pMsg->MsgId) 
  {
	  case WM_DELETE:
		// USER START (Optionally insert additional code for further widget initialization)
			key_flag=1;
			OS_INFO("KEYapp delete\n");
			Flag_ICON100 = 0;
			UserApp_Flag = 0;	
			PasswordFlags=0;
			Flag_ICON107 = 0;
			OK_Flag = 0;
			DeleteWindow_KEYBOARD();		
		// USER END
		    break;
	  case WM_INIT_DIALOG:
		//
		// Initialization of 'KEY TEST'
		//
		hItem = pMsg->hWin;
		FRAMEWIN_SetTextColor(hItem,GUI_DARKGRAY);
		FRAMEWIN_SetFont(hItem, GUI_FONT_16B_ASCII);
		FRAMEWIN_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,0);
		FRAMEWIN_SetTitleHeight(hItem, 20);
		
		hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT1);
		EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_BLUE);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		EDIT_SetFont(hItem, GUI_FONT_16B_ASCII);
		EDIT_SetTextMode(hItem);
		EDIT_SetText(hItem, "123qwe");
		
		hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON3);
		BUTTON_SetText(hItem, "确定");
		BUTTON_SetFont(hItem, &XBF_Font);
		
		// USER START (Optionally insert additional code for further widget initialization)
		key_flag=0;
		// USER END
		break;

	  	case WM_NOTIFY_PARENT:
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch(Id) {
			case GUI_ID_EDIT1: // Notifications sent by 'Edit'
			switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				messagesP[0]=WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT1);
				messagesP[1]=GUI_ID_EDIT1;
				if(!keypadflag)OSTaskQPost(&AppTaskKeypadTCB,
									(void *)&messagesP,
									2,
									OS_OPT_POST_FIFO,
									&err);
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;

		  case GUI_ID_BUTTON3: // Notifications sent by '确定'
		  switch(NCode) {
		  case WM_NOTIFICATION_CLICKED:

			break;
		  case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			EDIT_GetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT1), EnterPassword, 7);   // 获取字符串
			GET_AdministratorPassword(Password);                    // 读密码
			//printf("%s\n",Password);
			if (!strcmp(EnterPassword, (char *)Password))
			{
				/*密码正确*/
				WM_DeleteWindow(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT1));    //删除编辑框
				WM_DeleteWindow(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON3));   // 删除确认按键
				PasswordFlags = 1;
				PasswordManagement_Loop = 1;
				OK_Flag = 1;
				//PasswordManagement();
			}
			// USER END
			break;
		  case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END			    
				break;
		  }
		  break;
		// USER START (Optionally insert additional code for further Ids)
		// USER END
		}
		break;
	  // USER START (Optionally insert additional message handling)
		case WM_PAINT:	
			GUI_SetBkColor(APPBKCOLOR);
			GUI_SetColor(GUI_MAGENTA);
			GUI_SetColor(APPTEXTCOLOR);
			GUI_Clear();
			
			if (!PasswordFlags)
				GUI_DispStringAt("请输入管理员密码:",10,8);
		break;
	  // USER END
	  default:
		WM_DefaultProc(pMsg);
		break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateKEY TEST
*/
extern WM_HWIN hWinMiMa;
void FUN_ICON107Clicked(void)
{
	
	hWinMiMa = GUI_CreateDialogBox(_aDialogCreateSettings, GUI_COUNTOF(_aDialogCreateSettings), _cbDialogSET, WM_HBKWIN, 0, 0);
	OS_INFO("Fingerprint management create\n");
	OK_Flag = 0;
	while(Flag_ICON107)
	{
		if (OK_Flag)     // 等待密码正确
		{
			OK_Flag = 0;
			PasswordManagement();
		}
		GUI_Delay(10); 				
	}
}

void _cbDialogPasswordManagement(WM_MESSAGE * pMsg);

// USER START (Optionally insert additional public code)
/*********************************************************************
*
*       CreateKEY TEST
*/

void PasswordManagement(void)
{
	DeleteWindow_KEYBOARD();
	WM_DeleteWindow(hWinMiMa);
	Flag_ICON107=0;
	hWinMiMa = GUI_CreateDialogBox(_aDialogCreateIN, GUI_COUNTOF(_aDialogCreateIN), _cbDialogPasswordManagement, WM_HBKWIN, 0, 0);

	while(PasswordManagement_Loop)
	{	
		GUI_Delay(10);
	}
}

/* 对话框循环 */
u8 Dialog_Loop = 0;
void ChangeAdministratorPasswordDialog(void);    // 修改管理员密码
void ChangeOpenPasswordDialog(void);             // 修改开门密码

void _cbDialogPasswordManagement(WM_MESSAGE * pMsg)
{
	 WM_HWIN hItem;
  int     NCode;
  int     Id;

  // USER END

  switch (pMsg->MsgId) 
  {
	  case WM_DELETE:
		// USER START (Optionally insert additional code for further widget initialization)
		  key_flag=1;
		  PasswordManagement_Loop=0;
		  UserApp_Flag = 0;	
		  Flag_ICON100=0;
		// USER END
		    break;
	  case WM_INIT_DIALOG:
		//
		// Initialization of 'KEY TEST'
		//
		hItem = pMsg->hWin;
		FRAMEWIN_SetTextColor(hItem,GUI_DARKGRAY);
		FRAMEWIN_SetFont(hItem, GUI_FONT_16B_ASCII);
		FRAMEWIN_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,0);
		FRAMEWIN_SetTitleHeight(hItem, 20);
		//
		// Initialization of 'INIT'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON0);
		BUTTON_SetText(hItem, "修改管理员密码");
		BUTTON_SetFont(hItem, &XBF_Font);
		hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON1);
		BUTTON_SetText(hItem, "修改开门密码");
		BUTTON_SetFont(hItem, &XBF_Font);

		
		// USER START (Optionally insert additional code for further widget initialization)
		key_flag=0;
		// USER END
		break;
	  case WM_NOTIFY_PARENT:
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch(Id) 
		{
			case GUI_ID_BUTTON0: // 修改管理员密码
			  	switch(NCode) 
			  	{
					case WM_NOTIFICATION_CLICKED:

					break;
					case WM_NOTIFICATION_RELEASED:
					// USER START (Optionally insert code for reacting on notification message)
					Dialog_Loop=1;
					ChangeAdministratorPasswordDialog();
					//ErrorDialog(hWinMiMa,"no","no");
					// USER END
					break;
					case WM_NOTIFICATION_VALUE_CHANGED:
					// USER START (Optionally insert code for reacting on notification message)
					// USER END			    
					break;
				}
			break;
				
			case GUI_ID_BUTTON1: // 修改开门密码
				switch(NCode) 
				{
					case WM_NOTIFICATION_CLICKED:

					break;
					case WM_NOTIFICATION_RELEASED:
					// USER START (Optionally insert code for reacting on notification message)
					Dialog_Loop=1;
					ChangeOpenPasswordDialog();
					//Wipe_FingerprintData();
					
					// USER END
					break;
					case WM_NOTIFICATION_VALUE_CHANGED:
					// USER START (Optionally insert code for reacting on notification message)
					// USER END			    
					break;
		  		}
			break;
	  // USER START (Optionally insert additional message handling)
		case WM_PAINT:	
			GUI_SetBkColor(APPBKCOLOR);
			GUI_SetColor(GUI_MAGENTA);
			GUI_SetColor(APPTEXTCOLOR);
			GUI_Clear();
		break;
	  // USER END
	  default:
		WM_DefaultProc(pMsg);
		break;
  }
}
}

/* 修改管理员密码 */
 
#define ERROR_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ERROR_BUTTON_0   (GUI_ID_USER + 0x01)
#define ERROR_BUTTON_1   (GUI_ID_USER + 0x02)
 
static const GUI_WIDGET_CREATE_INFO _aDialogCreateCipher[] = {
	{ FRAMEWIN_CreateIndirect, "Change password",  ERROR_FRAMEWIN_0,  0, 0, 240, 320, 0, 0x0, 0 },
	{EDIT_CreateIndirect, 	"Edit", GUI_ID_EDIT2, 	10, 35, 160, 40, 0, 0x6, 0 }, 
	{ BUTTON_CreateIndirect, "OK", GUI_ID_BUTTON3, 180, 35, 40, 40, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, 	"state", GUI_ID_TEXT0, 	30, 80, 100, 50, 0, 0x64, 0 },
  //{ BUTTON_CreateIndirect,   "Reboot", ERROR_BUTTON_1,    180, 80,  60,  30,  0, 0x0, 0 },
};

static void _cbDialogAdministratorPassword(WM_MESSAGE * pMsg) 
{
	WM_HWIN hItem;
	int     NCode;
	int     Id;
	OS_ERR  err;
	u16 messagesP[2];
	char EnterPassword[14];    // 输入的密码
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) 
	{
		case WM_DELETE:
		// USER START (Optionally insert additional code for further widget initialization)
			key_flag=1;
			Dialog_Loop = 0;
			DeleteWindow_KEYBOARD();
			// USER END
		    break;

		case WM_INIT_DIALOG:
			//
			// Initialization of 'CLOSE'
			//
			hItem = pMsg->hWin;
			FRAMEWIN_SetTextColor(hItem,GUI_DARKGRAY);
			FRAMEWIN_SetFont(hItem, GUI_FONT_16B_ASCII);
			FRAMEWIN_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,0);
			FRAMEWIN_SetTitleHeight(hItem, 20);

			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT2);
			EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_BLUE);
			EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			EDIT_SetFont(hItem, GUI_FONT_16B_ASCII);
			EDIT_SetTextMode(hItem);
			EDIT_SetText(hItem, "qwerty");

			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON3);
			BUTTON_SetText(hItem, "确定");
			BUTTON_SetFont(hItem, &XBF_Font);

			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT0);
			TEXT_SetFont(hItem, &XBF_Font);
			TEXT_SetTextAlign(hItem, GUI_TA_CENTER | GUI_TA_VCENTER);
			TEXT_SetText(hItem, "");
			key_flag=0;
			// USER END
		break;

		case WM_NOTIFY_PARENT:
			Id    = WM_GetId(pMsg->hWinSrc);
			NCode = pMsg->Data.v;
			if(NCode==WM_NOTIFICATION_RELEASED)
			{
				switch(Id)
				{
					case GUI_ID_BUTTON3: // Notifications sent by '确定'
						switch(NCode) 
							{
								case WM_NOTIFICATION_CLICKED:

								break;
								case WM_NOTIFICATION_RELEASED:
								// USER START (Optionally insert code for reacting on notification message)
								/* 保存管理员密码 */
									SPI_FLASH_BufferRead((u8 *)EnterPassword, AdministratorPassword_Addr, 14);
									EDIT_GetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT2), EnterPassword, 7);   // 获取字符串
									SPI_FLASH_SectorErase(AdministratorPassword_Addr);                            // 擦除扇区
									SPI_FLASH_BufferWrite((u8 *)EnterPassword, AdministratorPassword_Addr, 14);   // 写数据
									hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT2);
									EDIT_SetText(hItem, "");                                                      // 清空输入框

									hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT0);
									TEXT_SetText(hItem,"密码设置成功");       // 提示密码设置成功
									TEXT_SetFont(hItem, &XBF_Font);
									TEXT_SetFont(hItem, &XBF_Font);          // 设置字体
								// USER END
								break;
								case WM_NOTIFICATION_VALUE_CHANGED:
								// USER START (Optionally insert code for reacting on notification message)
								// USER END
								break;
							}
						break;
					case GUI_ID_EDIT2: // Notifications sent by 'Edit'
						switch(NCode) 
						{
							case WM_NOTIFICATION_CLICKED:
								// USER START (Optionally insert code for reacting on notification message)
								// USER END
							break;
							
							case WM_NOTIFICATION_RELEASED:
								// USER START (Optionally insert code for reacting on notification message)
								messagesP[0]=WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT2);
								messagesP[1]=GUI_ID_EDIT2;
								if(!keypadflag)
									OSTaskQPost(&AppTaskKeypadTCB,
												(void *)&messagesP,
												2,
												OS_OPT_POST_FIFO,
												&err);
								// USER END
							break;

							case WM_NOTIFICATION_VALUE_CHANGED:
								// USER START (Optionally insert code for reacting on notification message)
								// USER END
							break;
						}
					break;
				}
			}    
		break;
	// USER START (Optionally insert additional message handling)
	case WM_PAINT:
			GUI_SetBkColor(APPBKCOLOR);
			GUI_SetColor(GUI_MAGENTA);
			GUI_SetColor(APPTEXTCOLOR);
			GUI_Clear();
			GUI_DispStringAt("请新的输入管理员密码:",10,8);
	break;
	// USER END
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}


void ChangeAdministratorPasswordDialog(void)
{
	GUI_CreateDialogBox(_aDialogCreateCipher,GUI_COUNTOF(_aDialogCreateCipher),_cbDialogAdministratorPassword,WM_HBKWIN,0,0);
//	WM_MakeModal(ADDhWin);
//	WM_SetStayOnTop(ADDhWin, 1);
	while(Dialog_Loop)
	{
		GUI_Delay(10);
	}
}

// USER END


/* 修改开门密码 */

static void _cbDialogOpenPassword(WM_MESSAGE * pMsg) 
{
	WM_HWIN hItem;
	int     NCode;
	int     Id;
	OS_ERR  err;
	u16 messagesP[2];
	char EnterPassword[14];    // 输入的密码
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) 
	{
		case WM_DELETE:
		// USER START (Optionally insert additional code for further widget initialization)
			key_flag=1;
			Dialog_Loop = 0;
			DeleteWindow_KEYBOARD();
			// USER END
		    break;

		case WM_INIT_DIALOG:
			//
			// Initialization of 'CLOSE'
			//
			hItem = pMsg->hWin;
			FRAMEWIN_SetTextColor(hItem,GUI_DARKGRAY);
			FRAMEWIN_SetFont(hItem, GUI_FONT_16B_ASCII);
			FRAMEWIN_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,0);
			FRAMEWIN_SetTitleHeight(hItem, 20);

			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT2);
			EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_BLUE);
			EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			EDIT_SetFont(hItem, GUI_FONT_16B_ASCII);
			//EDIT_SetUlongMode(hItem, 0, 0, 999999);
			EDIT_SetTextMode(hItem);
			EDIT_SetText(hItem, "123456");

			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON3);
			BUTTON_SetText(hItem, "确定");
			BUTTON_SetFont(hItem, &XBF_Font);

			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT0);
			TEXT_SetFont(hItem, &XBF_Font);
			TEXT_SetTextAlign(hItem, GUI_TA_CENTER | GUI_TA_VCENTER);
			TEXT_SetText(hItem, "");
			key_flag=0;
			// USER END
		break;

		case WM_NOTIFY_PARENT:
			Id    = WM_GetId(pMsg->hWinSrc);
			NCode = pMsg->Data.v;
			if(NCode==WM_NOTIFICATION_RELEASED)
			{
				switch(Id)
				{
					case GUI_ID_BUTTON3: // Notifications sent by '确定'
						switch(NCode) 
							{
								case WM_NOTIFICATION_CLICKED:

								break;
								case WM_NOTIFICATION_RELEASED:
								// USER START (Optionally insert code for reacting on notification message)
								/* 保存开门密码 */
									SPI_FLASH_BufferRead((u8 *)EnterPassword, AdministratorPassword_Addr, 14);
									//GET_AdministratorPassword();
									EDIT_GetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT2), &EnterPassword[7], 7);   // 获取输入字符串
									SPI_FLASH_SectorErase(AdministratorPassword_Addr);                            // 擦除扇区
									SPI_FLASH_BufferWrite((u8 *)EnterPassword, AdministratorPassword_Addr, 14);   // 写数据
									hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT2);
									EDIT_SetText(hItem, "");                                                      // 清空输入框

									hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT0);
									TEXT_SetText(hItem,"密码设置成功");       // 提示密码设置成功
									TEXT_SetFont(hItem, &XBF_Font);          // 设置字体
								// USER END
								break;
								case WM_NOTIFICATION_VALUE_CHANGED:
								// USER START (Optionally insert code for reacting on notification message)
								// USER END
								break;
							}
						break;
					case GUI_ID_EDIT2: // Notifications sent by 'Edit'
						switch(NCode) 
						{
							case WM_NOTIFICATION_CLICKED:
								// USER START (Optionally insert code for reacting on notification message)
								// USER END
							break;
							
							case WM_NOTIFICATION_RELEASED:
								// USER START (Optionally insert code for reacting on notification message)
								messagesP[0]=WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT2);
								messagesP[1]=GUI_ID_EDIT0;
								if(!keypadflag)
									OSTaskQPost(&AppTaskKeypadTCB,
												(void *)&messagesP,
												2,
												OS_OPT_POST_FIFO,
												&err);
								// USER END
							break;

							case WM_NOTIFICATION_VALUE_CHANGED:
								// USER START (Optionally insert code for reacting on notification message)
								// USER END
							break;
						}
					break;
				}
			}    
		break;
	// USER START (Optionally insert additional message handling)
	case WM_PAINT:
			GUI_SetBkColor(APPBKCOLOR);
			GUI_SetColor(GUI_MAGENTA);
			GUI_SetColor(APPTEXTCOLOR);
			GUI_Clear();
			GUI_DispStringAt("请新的输入开门密码:",10,8);
	break;
	// USER END
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}


void ChangeOpenPasswordDialog(void)
{
	GUI_CreateDialogBox(_aDialogCreateCipher,GUI_COUNTOF(_aDialogCreateCipher),_cbDialogOpenPassword,WM_HBKWIN,0,0);
//	WM_MakeModal(ADDhWin);
//	WM_SetStayOnTop(ADDhWin, 1);
	while(Dialog_Loop)
	{
		GUI_Delay(10);
	}
}

/*************************** End of file ****************************/
